package com.briup.apps.cms.bean;

public class BaseRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role.id
     *
     * @mbg.generated Tue Nov 19 11:03:52 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role.name
     *
     * @mbg.generated Tue Nov 19 11:03:52 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role.id
     *
     * @return the value of b_role.id
     *
     * @mbg.generated Tue Nov 19 11:03:52 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_role.id
     *
     * @param id the value for b_role.id
     *
     * @mbg.generated Tue Nov 19 11:03:52 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role.name
     *
     * @return the value of b_role.name
     *
     * @mbg.generated Tue Nov 19 11:03:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_role.name
     *
     * @param name the value for b_role.name
     *
     * @mbg.generated Tue Nov 19 11:03:52 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}